$menu = hyprlauncher
$terminal = ghostty
$fileManager = nautilus
$browser = brave

bind = SUPER, Q, killactive, 
bind = SUPER, Space, exec, $menu
bind = SUPER, B, exec, $browser
bind = SUPER, N, exec, $fileManager

# Focus
bind = ALT, Return, fullscreen,
bind = ALT+SHIFT, Return, togglefloating,

bind = SUPER, up, movefocus, u
bind = SUPER, down, movefocus, d
bind = SUPER, left, movefocus, l
bind = SUPER, right, movefocus, r

bind = ALT, TAB, movefocus, r
bind = ALT+SHIFT, TAB, movefocus, l
