$terminal = ghostty
$fileManager = nautilus
$menu = hyprlauncher

bind = SUPER, Q, killactive, 
bind = SUPER, Space, exec, $menu
bind = SUPER, N, exec, $fileManager

# Focus
bind = ALT, Enter, fullscreen,
bind = SUPER, up, movefocus, u
bind = SUPER, down, movefocus, d
bind = SUPER, left, movefocus, l
bind = SUPER, right, movefocus, r

bind = ALT, TAB, movefocus, r
bind = ALT+SHIFT, TAB, movefocus, l
