$terminal = ghostty
$fileManager = nautilus
$menu = hyprlauncher

bind = SUPER, Q, killactive, 			# todo: da valutare con piu schede
bind = SUPER, Space, exec, $terminal
bind = SUPER, N, exec, $fileManager

bind = SUPER, F, fullscreen,
bind = SUPER, up, movefocus, u
bind = SUPER, down, movefocus, d
bind = SUPER, left, movefocus, l
bind = SUPER, right, movefocus, r

bind = ALT, TAB, movefocus, r
bind = ALT+SHIFT, TAB, movefocus, l
